"""Generate scenarios/realistic_week.yaml: one week at realistic scale.

    python -m clustersim.realistic_week --config config/phase1.yaml \
        --out scenarios/realistic_week.yaml

Samples a full week from the calibrated workload model (same distributions
as the phase 1 trace generator) at the real GPU topology and a realistic
population: 26 trainers, 26 devs, 6 hoarders across the four WPs, CPU
users omitted (they do not appear on a GPU timeline). Multi-Pending gaming
is off so each timeline bar is one real request. The output is a plain
scenario YAML, every request listed with user, WP, pool, GPUs, submit
time, hold and utilization profile, so the week can be inspected and
hand-edited before running:

    python -m clustersim.scenario --scenario scenarios/realistic_week.yaml \
        --config config/phase1.yaml --out results/scenarios/realistic_week
"""

from __future__ import annotations

import argparse
import copy
from pathlib import Path

import yaml

from . import tracegen
from .plots import DAY_NAMES

H = 3600.0

GPU_POOLS = ("h100nvl", "mig3g", "mig1g", "h100sxm", "l40s")

USERS = {
    "trainers": {"count": 26, "jobs_per_day": 2.0},
    "devs": {"count": 26, "jobs_per_day": 2.0},
    "hoarders": {"count": 6, "jobs_per_day": 0.5},
    "cpu_batch": {"count": 0, "jobs_per_day": 0.0},
}

POLICIES = {
    "fcfs_pending": {},
    "ngt_principles_reclaim": {"reserve": {"h100nvl": 4, "l40s": 1},
                               "multi_gpu_cap_h": 24},
    "planning_cycle": {"reserve": {"h100nvl": 4, "l40s": 1},
                       "multi_gpu_cap_h": 24},
}


def daytime(t: float) -> str:
    day = int(t // 86400)
    hh = int(t % 86400 // H)
    mm = int(t % H // 60)
    return f"{DAY_NAMES[day % 7]} {hh:02d}:{mm:02d}"


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--config", required=True)
    ap.add_argument("--out", default="scenarios/realistic_week.yaml")
    args = ap.parse_args()
    config = yaml.safe_load(Path(args.config).read_text())

    gen_cfg = copy.deepcopy(config)
    gen_cfg["horizon_days"] = 7
    gen_cfg["workload"]["users"] = copy.deepcopy(USERS)
    for k in ("prob", "prob_dev", "prob_hoard"):
        gen_cfg["workload"]["gaming"][k] = 0.0
    gen_cfg["cluster"]["pools"] = {
        p: s for p, s in config["cluster"]["pools"].items() if p in GPU_POOLS}

    _, requests, cordons = tracegen.generate(gen_cfg)

    entries = []
    for r in sorted(requests, key=lambda r: r.submit_time):
        entries.append({
            "user": str(r.user), "wp": str(r.wp), "kind": str(r.kind),
            "pool": str(r.pool), "gpus": int(r.gpus),
            "time": daytime(r.submit_time),
            "hold_h": round(r.duration_s / H, 2),
            "patience_h": round(r.patience_s / H, 2),
            "profile": [[round(d / H, 3), round(u, 2)] for d, u in r.profile],
        })

    cordon_entries = []
    open_since: dict[str, float] = {}
    for c in sorted(cordons, key=lambda c: c.time):
        if c.cordoned:
            open_since[c.node_id] = c.time
        elif c.node_id in open_since:
            cordon_entries.append({"node": c.node_id,
                                   "from": daytime(open_since.pop(c.node_id)),
                                   "to": daytime(c.time)})
    for node, t in open_since.items():
        cordon_entries.append({"node": node, "from": daytime(t),
                               "to": "Sun 23:59"})

    scenario = {
        "name": "realistic-week",
        "description": (
            "One week at realistic scale: the current GPU topology "
            "(11 NVL nodes plus the MIG carve, 6 SXM, 7 L40S) and 58 GPU "
            "users in the calibrated composition (26 trainers, 26 devs, "
            "6 hoarders across the four WPs). Sampled from the phase 1 "
            f"workload model, seed {config['seed']}; gaming off so each "
            "bar is one real request; CPU flavors omitted. Generated by "
            "clustersim.realistic_week, safe to hand-edit."),
        "horizon_days": 7,
        "snapshot_interval_s": 1800,
        "cluster": {"pools": gen_cfg["cluster"]["pools"]},
        "policies": POLICIES,
        "requests": entries,
        "cordons": cordon_entries,
    }
    Path(args.out).write_text(yaml.safe_dump(scenario, sort_keys=False,
                                             width=100))
    print(f"wrote {args.out}: {len(entries)} requests, "
          f"{len(cordon_entries)} cordon windows, "
          f"{len({e['user'] for e in entries})} users")


if __name__ == "__main__":
    main()
